# 数据库配置
mysql:
 host: 'localhost'
 port: 3306
 user: 'root'
 password: 'your_password'
 database: 'scql'

# 服务器配置
server:
 host: "localhost"
 port: 80
 location: "https://scql.cpolar.top" 

# 用户信息文件
users_file_path: "./docker-compose/client/users.json"
# 用户列表
authorized_profile_path: "./authorized_profile.json"
