# 数据库配置
mysql:
 host: 'localhost'
 port: 3306
 user: 'root'
 password: 'WangHan@520'
 database: 'scql'

# 服务器配置
server:
 host: "localhost"
 port: 80
 location: "https://scql.cpolar.top" 

# 用户信息文件
users_file_path: "/Users/woodways/Desktop/scql-main/examples/docker-compose/client/users.json"
